name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this to your branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install  # or any command relevant to your project

    - name: Build project
      run: npm run build  # or any build command

    - name: Deploy to GitHub Pages
      uses: actions/configure-pages@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Adjust to your output directory

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push
